// Word Ladder: length of the shortest transformation sequence from beginWord to endWord,
// changing one letter at a time, every intermediate word in wordList. 0 if impossible.
// BFS over words; neighbors generated by trying all 26 letters at each position.
// O(N * L * 26) time (N words of length L, string building adds another factor L), O(N * L) space.

import 'dart:collection';

int ladderLength(String beginWord, String endWord, List<String> wordList) {
  final unvisited = wordList.toSet();
  if (!unvisited.contains(endWord)) return 0;
  final queue = Queue<(String, int)>()..add((beginWord, 1)); // (word, words in the sequence so far)
  unvisited.remove(beginWord);
  while (queue.isNotEmpty) {
    final (word, steps) = queue.removeFirst();
    if (word == endWord) return steps;
    final chars = word.codeUnits.toList();
    for (var i = 0; i < chars.length; i++) {
      final original = chars[i];
      for (var c = 97; c <= 122; c++) {
        if (c == original) continue;
        chars[i] = c;
        final next = String.fromCharCodes(chars);
        // Removing on enqueue (not on dequeue) keeps every word in the queue at most once.
        if (unvisited.remove(next)) queue.add((next, steps + 1));
      }
      chars[i] = original;
    }
  }
  return 0;
}

void check(Object? got, Object? want) {
  if ('$got' != '$want') throw StateError('expected $want, got $got');
  print('ok: $got');
}

void main() {
  // hit -> hot -> dot -> dog -> cog
  check(ladderLength('hit', 'cog', ['hot', 'dot', 'dog', 'lot', 'log', 'cog']), 5);
  check(ladderLength('hit', 'cog', ['hot', 'dot', 'dog', 'lot', 'log']), 0); // cog not in the list
  check(ladderLength('a', 'c', ['a', 'b', 'c']), 2);
  check(ladderLength('hot', 'dog', ['hot', 'dog']), 0); // two letters differ, no bridge
  check(ladderLength('red', 'tax', ['ted', 'tex', 'red', 'tax', 'tad', 'den', 'rex', 'pee']), 4);
}
